CREATE TABLE LESSONDETAILS (
    id INT PRIMARY KEY,
    lesson_name VARCHAR(100),
    lesson_description VARCHAR(255)
);

INSERT INTO LESSONDETAILS (id, lesson_name, lesson_description) 
VALUES (1, 'INTRODUCTION TO PROGRAMMING', 'LEARN THE BASICS OF PROGRAMMING');

INSERT INTO LESSONDETAILS (id, lesson_name, lesson_description) 
VALUES (2, 'DATA STRUCTURE AND ALGORITHM', 'FUNDAMENTALS OF DATA STRUCTURE');

INSERT INTO LESSONDETAILS (id, lesson_name, lesson_description) 
VALUES (3, 'OPERATING SYSTEM', 'PRINCIPALS OF THE OPERATING SYSTEMS');
