INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
					 (1, 'JAVA FULL STACK', '6 MONTHS', 22000);

INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
				 	 (2, 'PYTHON FULL STACK', '6 MONTHS', 20000);
				 	 
INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
					 (3, 'DEVOPS', '5 MONTHS', 15000);

INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE) VALUES 
				 	 (4, 'POWERBI', '3 MONTHS', 15000);
				 	 
INSERT INTO COURSE_DETAILS (ID, COURSE_NAME, COURSE_DURIATION, COURSE_PRICE ) VALUES 
				 	 (5, 'AWS', '6 MONTHS', 18000);
