CREATE TABLE COURSEDETAILS (
    ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(255),
    COURSE_DESCRIPTION VARCHAR(255),
    COURSE_INSTRUCTOR VARCHAR(255)
);

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES (1, 'Web development', 'creating web pages', 'john doe');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES (2, 'development', 'creating web pages', 'doe');

INSERT INTO COURSEDETAILS(ID, COURSE_NAME, COURSE_DESCRIPTION, COURSE_INSTRUCTOR)
VALUES (3, 'Web', 'creating web pages', 'john');
